FILTER_SANITIZE_ENCODED
  INSERT FILTER_SANITIZE_ENCODED
  constant
FILTER_SANITIZE_FULL_SPECIAL_CHARS
  INSERT FILTER_SANITIZE_FULL_SPECIAL_CHARS
  constant
FILTER_SANITIZE_MAGIC_QUOTES
  INSERT FILTER_SANITIZE_MAGIC_QUOTES
  constant
FILTER_SANITIZE_NUMBER_FLOAT
  INSERT FILTER_SANITIZE_NUMBER_FLOAT
  constant
FILTER_SANITIZE_NUMBER_INT
  INSERT FILTER_SANITIZE_NUMBER_INT
  constant
FILTER_SANITIZE_SPECIAL_CHARS
  INSERT FILTER_SANITIZE_SPECIAL_CHARS
  constant
FILTER_SANITIZE_STRING
  INSERT FILTER_SANITIZE_STRING
  constant
FILTER_SANITIZE_STRIPPED
  INSERT FILTER_SANITIZE_STRIPPED
  constant
FILTER_SANITIZE_URL
  INSERT FILTER_SANITIZE_URL
  constant
FILTER_UNSAFE_RAW
  INSERT FILTER_UNSAFE_RAW
  constant
FILTER_VALIDATE_BOOLEAN
  INSERT FILTER_VALIDATE_BOOLEAN
  constant
FILTER_VALIDATE_EMAIL
  INSERT FILTER_VALIDATE_EMAIL
  constant
FILTER_VALIDATE_FLOAT
  INSERT FILTER_VALIDATE_FLOAT
  constant
FILTER_VALIDATE_INT
  INSERT FILTER_VALIDATE_INT
  constant
FILTER_VALIDATE_IP
  INSERT FILTER_VALIDATE_IP
  constant
FILTER_VALIDATE_MAC
  INSERT FILTER_VALIDATE_MAC
  constant
FILTER_VALIDATE_REGEXP
  INSERT FILTER_VALIDATE_REGEXP
  constant
FILTER_VALIDATE_URL
  INSERT FILTER_VALIDATE_URL
  constant
FORCE_DEFLATE
  INSERT FORCE_DEFLATE
  constant
FORCE_GZIP
  INSERT FORCE_GZIP
  constant
FilesystemIterator
  INSERT FilesystemIterator
  class
FilterIterator
  INSERT FilterIterator
  class
Foo
  INSERT Foo
  class
FunctionCredential
  INSERT FunctionCredential
  class
false
  INSERT false
  constant
fb_call_user_func_async
  INSERT fb_call_user_func_async
  function
fb_compact_serialize
  INSERT fb_compact_serialize
  function
fb_compact_unserialize
  INSERT fb_compact_unserialize
  function
fb_disable_code_coverage
  INSERT fb_disable_code_coverage
  function
fb_enable_code_coverage
  INSERT fb_enable_code_coverage
  function
fb_gen_user_func
  INSERT fb_gen_user_func
  function
fb_get_code_coverage
  INSERT fb_get_code_coverage
  function
fb_get_last_flush_size
  INSERT fb_get_last_flush_size
  function
fb_intercept2
  INSERT fb_intercept2
  function
fb_intercept2_named_args
  INSERT fb_intercept2_named_args
  function
fb_output_compression
  INSERT fb_output_compression
  function
fb_rename_function
  INSERT fb_rename_function
  function
fb_serialize
  INSERT fb_serialize
  function
fb_set_exit_callback
  INSERT fb_set_exit_callback
  function
fb_setprofile
  INSERT fb_setprofile
  function
fb_unserialize
  INSERT fb_unserialize
  function
fb_utf8_strlen
  INSERT fb_utf8_strlen
  function
fb_utf8_substr
  INSERT fb_utf8_substr
  function
fb_utf8ize
  INSERT fb_utf8ize
  function
fclose
  INSERT fclose
  function
feof
  INSERT feof
  function
fflush
  INSERT fflush
  function
fgetc
  INSERT fgetc
  function
fgetcsv
  INSERT fgetcsv
  function
fgets
  INSERT fgets
  function
fgetss
  INSERT fgetss
  function
file
  INSERT file
  function
file_exists
  INSERT file_exists
  function
file_get_contents
  INSERT file_get_contents
  function
file_put_contents
  INSERT file_put_contents
  function
fileatime
  INSERT fileatime
  function
filectime
  INSERT filectime
  function
filegroup
  INSERT filegroup
  function
fileinode
  INSERT fileinode
  function
filemtime
  INSERT filemtime
  function
fileowner
  INSERT fileowner
  function
fileperms
  INSERT fileperms
  function
filesize
  INSERT filesize
  function
filetype
  INSERT filetype
  function
filter_has_var
  INSERT filter_has_var
  function
filter_id
  INSERT filter_id
  function
filter_input
  INSERT filter_input
  function
filter_input_array
  INSERT filter_input_array
  function
filter_list
  INSERT filter_list
  function
filter_var
  INSERT filter_var
  function
filter_var_array
  INSERT filter_var_array
  function
finfo
  INSERT finfo
  class
finfo_buffer
  INSERT finfo_buffer
  function
finfo_close
  INSERT finfo_close
  function
finfo_file
  INSERT finfo_file
  function
finfo_open
  INSERT finfo_open
  function
finfo_set_flags
  INSERT finfo_set_flags
  function
floatval
  INSERT floatval
  function
flock
  INSERT flock
  function
floor
  INSERT floor
  function
flush
  INSERT flush
  function
fmod
  INSERT fmod
  function
fnmatch
  INSERT fnmatch
  function
fopen
  INSERT fopen
  function
fpassthru
  INSERT fpassthru
  function
fprintf
  INSERT fprintf
  function
fputcsv
  INSERT fputcsv
  function
fputs
  INSERT fputs
  function
fread
  INSERT fread
  function
fscanf
  INSERT fscanf
  function
fseek
  INSERT fseek
  function
fsockopen
  INSERT fsockopen
  function
fstat
  INSERT fstat
  function
ftell
  INSERT ftell
  function
ftok
  INSERT ftok
  function
ftruncate
  INSERT ftruncate
  function
function_exists
  INSERT function_exists
  function
furchash_hphp_ext
  INSERT furchash_hphp_ext
  function
furchash_hphp_ext_supported
  INSERT furchash_hphp_ext_supported
  function
fwrite
  INSERT fwrite
  function
function
  INSERT function
  keyword
