[package]
name = "hhvm_ffi_bridge"
version = "0.0.0"
edition = "2024"

[lib]
path = "lib.rs"
crate-type = ["staticlib", "rlib"]

[dependencies]
compiler_ffi = { path = "../hackc/ffi_bridge" }
hdf = { path = "../utils/hdf" }
hhvm_hhbc_defs_ffi = { path = "../hackc/hhvm_cxx/hhvm_hhbc_defs" }
hhvm_types_ffi = { path = "../hackc/hhvm_cxx/hhvm_types" }
packages_ffi = { path = "../packages/ffi_bridge" }
parser_ffi = { path = "../parser/ffi_bridge" }
