File "redundant_cast_placeholder.php", line 20, characters 3-21:
This `as` assertion will always succeed and hence is redundant. The expression on the left has a type `C<nothing, nothing, mixed>` which is a subtype of `C<nothing, nothing, nothing>`. (Lint[5628])
File "redundant_cast_placeholder.php", line 21, characters 3-21:
This `as` assertion will always succeed and hence is redundant. The expression on the left has a type `D<nothing, mixed>` which is a subtype of `C<nothing, int, nothing>`. (Lint[5628])
File "redundant_cast_placeholder.php", line 22, characters 3-21:
This `as` assertion will always succeed and hence is redundant. The expression on the left has a type `E` which is a subtype of `C<bool, int, nothing>`. (Lint[5628])
File "redundant_cast_placeholder.php", line 23, characters 3-16:
This `as` assertion will always succeed and hence is redundant. The expression on the left has a type `E` which is a subtype of `C<bool, int, nothing>`. (Lint[5628])
